### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by cainlevy** [percy/react-percy#104]
Attempting to use awesome-typescript-loader to integrate Percy with a TypeScript project yields:

> Error: It looks like you're using an old webpack version without hooks support. If you're using awesome-script-loader with React storybooks consider upgrading @storybook/react to at least version 4.0.0-alpha.3

percy.config.js:

```
const path = require('path');

exports.default = {
  webpack: {
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx'],
      alias: {
        Public: path.resolve(__dirname, '../public/'),
      },
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          loader: 'awesome-typescript-loader',
          exclude: /(node_modules)/,
          options: {
            useCache: true,
            cacheDirectory: './.cache/awesome-typescript-loader',
          },
        }
      ]
    }
  }
}
```

**Comment by matheusml** [comment]
Same here. @cainlevy did you manage to fix that?

**Comment by cainlevy** [comment]
Negative: https://github.com/percy/react-percy/commit/66a5c0c4f0ac8b38155314f7e63c61c6f8494f24
