### ISSUE TITLE
inPercy not working?

### ISSUE THREAD

**Issue by joscha** [percy/react-percy#39]
Lately, it seems as if inPercy() does not work any more properly - is there a chance you changed the host from `proxyme.percy.io` to something else on your build machines and that's why it is not working @timhaines?

**Comment by timhaines** [comment]
Hi @joscha.  We haven't changed proxymy.percy.io.  I'm happy to help you narrow in on what the problem may be here.

We have an example repo that runs our storybook snapshots in our CI process.  Part of the config is mocking the date inside an inPercy() condition, and it resulted in the diffs that were expected.  The commit for that was [here](https://github.com/percy/react-percy/pull/40/files).

Are there other things that have changed in your config (or perhaps a Storybook update to an alpha?) that may account for this?

**Comment by timhaines** [comment]
@joscha As an option worth exploring (perhaps later after some easier options explored), feel welcome to make a simple reproduction repo and I'll be happy to troubleshoot from there.

**Comment by joscha** [comment]
I can't reproduce it right now - not sure what I saw...will reopen if it becomes a problem again. Thanks @timhaines!
