### ISSUE TITLE
in-percy: unspecified babel dependency

### ISSUE THREAD

**Issue by joscha** [percy/react-percy#68]
I am getting:
```
ERROR in 'babel-runtime/helpers/typeof' is imported by node_modules/@percy-io/in-percy/lib/index.js, but could not be resolved – treating it as an external dependency
```
with the latest in-percy `0.1.5`.

When looking at the `lib` folder I see:

```
var _typeof2 = require('babel-runtime/helpers/typeof');

var _typeof3 = _interopRequireDefault(_typeof2);
```
Ideally I think we wouldn't even need this, but if we do, `babel-runtime` has to become a `dependency`.

**Comment by timhaines** [comment]
@joscha Thanks for bringing this to our attention.  We'll discuss a few options and publish an update.  I agree, having babel-runtime be a dependency here doesn't sound appropriate.

**Comment by timhaines** [comment]
@joscha I've just shipped 0.1.6 which now has a correctly configured dependency on 'babel-runtime'.  Percy-storybook also has dependency on it (now correctly specified).

We may consider moving in-percy out of this repo and removing the babel-runtime requirement in the future - and could do it more urgently if it's causing you issues.  

Can you let me know via email if you're using in-percy outside of percy-storybook?  I'm curious to learn how you became aware of this problem.

**Comment by joscha** [comment]
Hi Tim,

That's unfortunate as babel-runtime shouldn't be needed - it's a
three-liner with a `typeof window` that should work in IE8 even. I will
need to check but that might actually render it useless for us so o have to
change the setup. The reason we use it outside storybook is that we have
shared code for Visreg detection in both storybook and our other pages that
we test with capybara - this is more due to the fact of laziness though
because three lines of code didn't warrant splitting that code up. With
babel-runtime in the game I will revisit.

Cheers,
Joscha

**Comment by timhaines** [comment]
Hey Joscha,  Oh, okay.  Now I know how it's causing problems, give me a day or two and I'll prioritize splitting the package out to it own repo and removing babel-runtime.  I'll let you know once I have.

**Comment by timhaines** [comment]
@joscha in-percy 0.1.7 has been published - it no longer uses babel.

**Comment by joscha** [comment]
Awesome :tada:, thanks a lot!
